#!/usr/bin/env python3
"""Hackathon-focused X collector.

Priorities:
1. Known handle crawler (best-effort no-login discovery + optional RSS)
2. Query/dork discovery
3. Nitter/XCancel RSS quick check
4. FxTwitter enrichment for stable structured tweet payloads

This collector is intentionally pragmatic for the hackathon case.
It favors public/no-login collection paths and falls back to a bootstrap URL list
for reliable enrichment when search indexing is inconsistent.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import re
import sys
import time
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable
from urllib.parse import urlparse

import requests
from bs4 import BeautifulSoup

DEFAULT_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}

HANDLES = [
    "AnthropicAI",
    "ClaudeAI",
    "sama",
    "karpathy",
    "swyx",
    "goodside",
    "simonw",
    "demishassabis",
    "OpenAI",
    "GregBrockman",
    "ylecun",
    "drjimfan",
    "amasad",
    "skirano",
    "natfriedman",
    "danielgross",
    "jxnlco",
    "ilyasut",
    "gdb",
    "miramurati",
]


_REPO_ROOT = Path(__file__).parent.parent
_RAW_DIR   = _REPO_ROOT / "data" / "raw"
_WATCHLIST = _REPO_ROOT / "data" / "amplifier_watchlist.csv"


def load_watchlist_handles(path: str | None = None) -> list[str]:
    """Load handles from amplifier_watchlist.csv (auto-generated by analysis/amplifier_watchlist.py).
    Returns empty list if file doesn't exist — scraper falls back to HANDLES above."""
    import csv as _csv
    p = Path(path) if path else _WATCHLIST
    if not p.exists():
        return []
    handles = []
    with p.open(encoding="utf-8") as f:
        for row in _csv.DictReader(f):
            h = (row.get("handle") or "").strip().lstrip("@")
            if h:
                handles.append(h)
    return handles

DORK_QUERIES = [
    'site:x.com "Claude AI"',
    'site:x.com "Anthropic Claude"',
    'site:x.com "Claude Code"',
    'site:x.com "Claude vs ChatGPT"',
    'site:x.com "switched to Claude"',
    'site:x.com "vibe coding"',
    'site:x.com "Claude refused"',
    'site:x.com "Claude better than GPT"',
    'site:x.com "using Claude"',
    'site:x.com "Claude API"',
    'site:x.com "claude.ai"',
    'site:x.com "Claude 3"',
    'site:x.com "claude sonnet"',
    'site:x.com "claude opus"',
    'site:x.com "@AnthropicAI"',
    'site:x.com "Claude Haiku"',
    'site:x.com "Claude is better"',
    'site:x.com "Claude wrote"',
    'site:x.com "Claude generated"',
    'site:x.com "Anthropic" AI assistant',
    'site:x.com "claude coding"',
    'site:x.com "claude helped"',
]

HANDLE_QUERY_TEMPLATES = [
    'site:twitter.com/{handle}/status Claude',
    'site:x.com/{handle}/status Claude',
    'site:twitter.com/{handle}/status',
    'site:x.com/{handle}/status',
]

NITTER_RSS_CANDIDATES = [
    'https://xcancel.com',
    'https://nitter.poast.org',
    'https://nitter.tiekoetter.com',
]

STATUS_URL_RE = re.compile(
    r'https?://(?:www\.)?(?:x|twitter)\.com/(?:(?P<handle>[A-Za-z0-9_]{1,15})/)?status/(?P<tweet_id>\d{5,25})(?:[/?#].*)?$',
    re.IGNORECASE,
)


@dataclass
class CollectedTweet:
    platform: str
    tweet_id: str
    author_handle: str
    author_name: str
    text: str
    created_at: str
    url: str
    is_official: bool
    source_query: str
    has_media: bool
    outbound_links: list[str]
    likes: int
    retweets: int
    replies: int
    views: int
    bookmarks: int
    author_followers: int


@dataclass
class DiscoveryHit:
    url: str
    source_query: str
    source: str


def dedupe_preserve_order(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            out.append(value)
    return out


def canonicalize_status_url(raw_url: str) -> tuple[str, str] | None:
    url = raw_url.strip()
    if url.startswith("//"):
        url = f"https:{url}"
    match = STATUS_URL_RE.match(url)
    if not match:
        parsed = urlparse(url)
        path_parts = [part for part in parsed.path.split("/") if part]
        tweet_id = next((part for part in path_parts if part.isdigit() and len(part) >= 5), None)
        if not tweet_id:
            return None
        return f"https://x.com/i/status/{tweet_id}", tweet_id
    handle = match.group("handle")
    tweet_id = match.group("tweet_id")
    if handle and handle.lower() == "status":
        handle = None
    return (f"https://x.com/{handle}/status/{tweet_id}" if handle else f"https://x.com/i/status/{tweet_id}", tweet_id)


def polite_sleep(base_seconds: float) -> None:
    if base_seconds > 0:
        time.sleep(base_seconds + random.uniform(0.05, 0.35))


def get_all_handles() -> list[str]:
    """Merge static HANDLES with auto-discovered watchlist handles (deduped)."""
    watchlist = load_watchlist_handles()
    merged = list(HANDLES) + [h for h in watchlist if h.lower() not in {x.lower() for x in HANDLES}]
    if watchlist:
        new_handles = [h for h in watchlist if h.lower() not in {x.lower() for x in HANDLES}]
        if new_handles:
            print(f'[watchlist] loaded {len(new_handles)} new handles from amplifier_watchlist.csv', file=sys.stderr)
    return merged


def handle_queries() -> list[str]:
    queries: list[str] = []
    for handle in get_all_handles():
        for template in HANDLE_QUERY_TEMPLATES:
            queries.append(template.format(handle=handle))
    return dedupe_preserve_order(queries)


def bootstrap_hits(path: Path) -> list[DiscoveryHit]:
    if not path.exists():
        return []
    hits: list[DiscoveryHit] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        normalized = canonicalize_status_url(line)
        if not normalized:
            continue
        url, _ = normalized
        hits.append(DiscoveryHit(url=url, source_query='bootstrap:manual_seed', source='bootstrap'))
    return hits


def ddg_search(session: requests.Session, query: str, page: int = 0) -> list[DiscoveryHit]:
    offset = page * 30
    response = session.post(
        'https://html.duckduckgo.com/html/',
        data={'q': query, 's': str(offset)},
        headers={**DEFAULT_HEADERS, 'Referer': 'https://duckduckgo.com/'},
        timeout=30,
    )
    if response.status_code != 200:
        return []
    soup = BeautifulSoup(response.text, 'lxml')
    hits: list[DiscoveryHit] = []
    for link in soup.select('a.result__a'):
        href = link.get('href')
        if not href:
            continue
        normalized = canonicalize_status_url(href)
        if not normalized:
            continue
        url, _ = normalized
        hits.append(DiscoveryHit(url=url, source_query=query, source='duckduckgo_html'))
    return hits


TWITTER_URL_IN_HTML_RE = re.compile(
    r'https?://(?:www\.)?(?:twitter\.com|x\.com)/[A-Za-z0-9_]{1,15}/status/\d{5,25}'
)


def brave_search(session: requests.Session, query: str) -> list[DiscoveryHit]:
    response = session.get(
        'https://search.brave.com/search',
        params={'q': query},
        headers=DEFAULT_HEADERS,
        timeout=30,
    )
    if response.status_code != 200:
        return []
    html = response.text.replace('\\/', '/')
    urls = dedupe_preserve_order(TWITTER_URL_IN_HTML_RE.findall(html))
    hits: list[DiscoveryHit] = []
    for url in urls:
        normalized = canonicalize_status_url(url)
        if not normalized:
            continue
        clean_url, _ = normalized
        hits.append(DiscoveryHit(url=clean_url, source_query=query, source='brave_html'))
    return hits


def bing_search(session: requests.Session, query: str, page: int = 0) -> list[DiscoveryHit]:
    offset = page * 10
    response = session.get(
        'https://www.bing.com/search',
        params={'q': query, 'first': str(offset + 1)},
        headers=DEFAULT_HEADERS,
        timeout=30,
    )
    if response.status_code != 200:
        return []
    soup = BeautifulSoup(response.text, 'lxml')
    hits: list[DiscoveryHit] = []
    for result in soup.select('li.b_algo'):
        link = result.select_one('h2 a')
        if not link:
            continue
        href = link.get('href')
        if not href:
            continue
        normalized = canonicalize_status_url(href)
        if not normalized:
            continue
        url, _ = normalized
        hits.append(DiscoveryHit(url=url, source_query=query, source='bing_html'))
    return hits


def discover_hits(session: requests.Session, query: str, pages: int) -> list[DiscoveryHit]:
    hits: list[DiscoveryHit] = []
    seen_urls: set[str] = set()

    for page in range(max(pages, 1)):
        for finder in (ddg_search, bing_search):
            try:
                page_hits = finder(session, query, page)
            except Exception:
                page_hits = []
            for hit in page_hits:
                if hit.url in seen_urls:
                    continue
                seen_urls.add(hit.url)
                hits.append(hit)
        polite_sleep(0.3)

    # Brave fallback is single-page and best-effort only.
    try:
        for hit in brave_search(session, query):
            if hit.url in seen_urls:
                continue
            seen_urls.add(hit.url)
            hits.append(hit)
    except Exception:
        pass

    return hits


def check_nitter_rss(session: requests.Session, handle: str = 'AnthropicAI') -> tuple[str | None, str]:
    reasons: list[str] = []
    for base in NITTER_RSS_CANDIDATES:
        url = f'{base}/{handle}/rss'
        try:
            response = session.get(url, headers=DEFAULT_HEADERS, timeout=20)
        except Exception as exc:  # noqa: BLE001
            reasons.append(f'{base} request failed')
            continue
        ctype = (response.headers.get('content-type') or '').lower()
        text = response.text[:1500]
        if response.status_code == 200 and 'rss' in ctype and 'whitelisted' not in text.lower() and 'not a bot' not in text.lower():
            return base, 'ok'
        if 'whitelisted' in text.lower():
            reasons.append(f'{base} requires RSS whitelist')
            continue
        if 'not a bot' in text.lower() or 'verifying your browser' in text.lower():
            reasons.append(f'{base} blocked by anti-bot gate')
            continue
        reasons.append(f'{base} unavailable')
    return None, '; '.join(reasons) if reasons else 'no working public rss instance found'


def fetch_nitter_rss(session: requests.Session, base_url: str, handle: str, limit: int) -> list[DiscoveryHit]:
    url = f'{base_url}/{handle}/rss'
    response = session.get(url, headers=DEFAULT_HEADERS, timeout=20)
    response.raise_for_status()
    root = ET.fromstring(response.text)
    hits: list[DiscoveryHit] = []
    for item in root.findall('./channel/item')[:limit]:
        link = (item.findtext('link') or '').strip()
        normalized = canonicalize_status_url(link)
        if not normalized:
            continue
        clean_url, _ = normalized
        hits.append(DiscoveryHit(url=clean_url, source_query=f'nitter_rss:{handle}', source='nitter_rss'))
    return hits


def fetch_fxtwitter_tweet(session: requests.Session, status_url: str, source_query: str) -> CollectedTweet | None:
    normalized = canonicalize_status_url(status_url)
    if not normalized:
        return None
    clean_url, tweet_id = normalized
    parsed = urlparse(clean_url)
    parts = [part for part in parsed.path.split('/') if part]
    handle = parts[0] if len(parts) >= 3 else 'i'
    api_url = f'https://api.fxtwitter.com/{handle}/status/{tweet_id}' if handle != 'i' else f'https://api.fxtwitter.com/i/status/{tweet_id}'

    response = session.get(api_url, headers=DEFAULT_HEADERS, timeout=30)
    if response.status_code != 200:
        return None
    payload = response.json()
    if payload.get('code') != 200 or 'tweet' not in payload:
        return None

    tweet = payload['tweet']
    author = tweet.get('author', {}) or {}
    raw_text = tweet.get('raw_text', {}) or {}

    outbound_links: list[str] = []
    for facet in raw_text.get('facets', []) or []:
        if facet.get('type') == 'url' and facet.get('replacement'):
            outbound_links.append(facet['replacement'])
    card = tweet.get('card') or {}
    if card.get('url'):
        outbound_links.append(card['url'])
    quote = tweet.get('quote') or {}
    quote_card = quote.get('card') or {}
    if quote_card.get('url'):
        outbound_links.append(quote_card['url'])

    has_media = bool(tweet.get('media') or tweet.get('twitter_card') in {'photo', 'video'} or card.get('image'))

    author_handle = author.get('screen_name') or handle
    return CollectedTweet(
        platform='x',
        tweet_id=str(tweet.get('id') or tweet_id),
        author_handle=author_handle,
        author_name=author.get('name') or author_handle,
        text=tweet.get('text') or '',
        created_at=tweet.get('created_at') or '',
        url=tweet.get('url') or clean_url,
        is_official=author_handle.lower() in {'anthropicai', 'claudeai'},
        source_query=source_query,
        has_media=has_media,
        outbound_links=dedupe_preserve_order(outbound_links),
        likes=int(tweet.get('likes') or 0),
        retweets=int(tweet.get('retweets') or 0),
        replies=int(tweet.get('replies') or 0),
        views=int(tweet.get('views') or 0),
        bookmarks=int(tweet.get('bookmarks') or 0),
        author_followers=int(author.get('followers') or 0),
    )


def write_json(path: Path, rows: Iterable[CollectedTweet]) -> None:
    path.write_text(json.dumps([asdict(row) for row in rows], ensure_ascii=False, indent=2), encoding='utf-8')


def write_csv(path: Path, rows: Iterable[CollectedTweet]) -> None:
    rows_list = [asdict(row) for row in rows]
    if not rows_list:
        path.write_text('', encoding='utf-8')
        return
    with path.open('w', encoding='utf-8', newline='') as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows_list[0].keys()))
        writer.writeheader()
        writer.writerows(rows_list)


def main() -> int:
    parser = argparse.ArgumentParser(description='Collect public X data for the hackathon case.')
    parser.add_argument('--pages', type=int, default=3, help='Search pages per query.')
    parser.add_argument('--limit-per-query', type=int, default=25, help='Max tweet URLs accepted per query.')
    parser.add_argument('--limit-per-handle-rss', type=int, default=50, help='Max RSS items per handle when RSS works.')
    _raw = _REPO_ROOT / "data" / "raw"
    parser.add_argument('--bootstrap-urls', default=str(_REPO_ROOT / 'scrapers' / 'x_bootstrap_urls.txt'), help='Optional bootstrap URLs file.')
    parser.add_argument('--output-json', default=str(_raw / 'x_case_raw.json'), help='Output JSON path.')
    parser.add_argument('--output-csv',  default=str(_raw / 'x_case_raw.csv'),  help='Output CSV path.')
    parser.add_argument('--verbose', action='store_true')
    args = parser.parse_args()

    session = requests.Session()
    session.headers.update(DEFAULT_HEADERS)

    discovered: list[DiscoveryHit] = []
    seen_urls: set[str] = set()

    # Priority 0: reliable bootstrap URLs.
    for hit in bootstrap_hits(Path(args.bootstrap_urls)):
        if hit.url not in seen_urls:
            seen_urls.add(hit.url)
            discovered.append(hit)

    # Priority 1: known handles.
    rss_base, rss_status = check_nitter_rss(session)
    if args.verbose:
        print(f'[rss-check] {rss_status}', file=sys.stderr)
    if rss_base:
        for handle in get_all_handles():
            try:
                for hit in fetch_nitter_rss(session, rss_base, handle, args.limit_per_handle_rss):
                    if hit.url in seen_urls:
                        continue
                    seen_urls.add(hit.url)
                    discovered.append(hit)
            except Exception as exc:  # noqa: BLE001
                if args.verbose:
                    print(f'[warn] rss fetch failed for {handle}: {exc}', file=sys.stderr)

    for query in handle_queries() + DORK_QUERIES:
        try:
            hits = discover_hits(session, query, args.pages)
        except Exception as exc:  # noqa: BLE001
            if args.verbose:
                print(f'[warn] discovery failed for {query!r}: {exc}', file=sys.stderr)
            continue
        accepted = 0
        for hit in hits:
            if hit.url in seen_urls:
                continue
            seen_urls.add(hit.url)
            discovered.append(hit)
            accepted += 1
            if accepted >= args.limit_per_query:
                break
        if args.verbose:
            print(f'[discover] query={query!r} accepted={accepted}', file=sys.stderr)
        polite_sleep(0.25)

    rows: list[CollectedTweet] = []
    seen_tweet_ids: set[str] = set()
    for hit in discovered:
        tweet = fetch_fxtwitter_tweet(session, hit.url, hit.source_query)
        if not tweet or not tweet.text:
            continue
        if tweet.tweet_id in seen_tweet_ids:
            continue
        seen_tweet_ids.add(tweet.tweet_id)
        rows.append(tweet)
        if args.verbose:
            print(f'[ok] @{tweet.author_handle} {tweet.tweet_id} source={tweet.source_query}', file=sys.stderr)
        polite_sleep(0.15)

    write_json(Path(args.output_json), rows)
    write_csv(Path(args.output_csv), rows)
    print(json.dumps({
        'discovered_urls': len(discovered),
        'collected_rows': len(rows),
        'output_json': args.output_json,
        'output_csv': args.output_csv,
        'rss_status': rss_status,
        'rss_base': rss_base,
    }, ensure_ascii=False))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
